name: Get Changed Files
description: Get all files changed/modified in a pull request or push's commits. This project is a fork of https://github.com/jitterbit/get-changedfiles, which supports pull_request_target and allow to filter files using regular expressions
author: Jitterbit, Inc.
branding:
  icon: file
  color: purple
runs:
  using: node12
  main: dist/index.js
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  format:
    description: >
      Format of the steps output context.
      Can be 'space-delimited', 'csv', or 'json'.
    required: true
    default: space-delimited
  filter:
    required: true
    default: '*'
outputs:
  all:
    description: >
      Array of all changed files.
  added:
    description: >
      Array of added files.
  modified:
    description: >
      Array of modified files.
  removed:
    description: >
      Array of removed files.
  renamed:
    description: >
      Array of renamed files.
  added_modified:
    description: >
      Array of all added and modified files.
  # For backwards-compatibility
  deleted:
    description: >
      Array of deleted files.
